#pragma once

#include "../Engine/Define.h"
#include "../Engine/StandardInclude.h"
#include "../Engine/SDL_Include.h"

namespace BSE
{
    enum class KeyCode
    {
        UNKNOWN = SDL_SCANCODE_UNKNOWN,

        A = SDL_SCANCODE_A, B = SDL_SCANCODE_B, C = SDL_SCANCODE_C,
        D = SDL_SCANCODE_D, E = SDL_SCANCODE_E, F = SDL_SCANCODE_F,
        G = SDL_SCANCODE_G, H = SDL_SCANCODE_H, I = SDL_SCANCODE_I,
        J = SDL_SCANCODE_J, K = SDL_SCANCODE_K, L = SDL_SCANCODE_L,
        M = SDL_SCANCODE_M, N = SDL_SCANCODE_N, O = SDL_SCANCODE_O,
        P = SDL_SCANCODE_P, Q = SDL_SCANCODE_Q, R = SDL_SCANCODE_R,
        S = SDL_SCANCODE_S, T = SDL_SCANCODE_T, U = SDL_SCANCODE_U,
        V = SDL_SCANCODE_V, W = SDL_SCANCODE_W, X = SDL_SCANCODE_X,
        Y = SDL_SCANCODE_Y, Z = SDL_SCANCODE_Z,

        NUM_0 = SDL_SCANCODE_0, NUM_1 = SDL_SCANCODE_1, NUM_2 = SDL_SCANCODE_2,
        NUM_3 = SDL_SCANCODE_3, NUM_4 = SDL_SCANCODE_4, NUM_5 = SDL_SCANCODE_5,
        NUM_6 = SDL_SCANCODE_6, NUM_7 = SDL_SCANCODE_7, NUM_8 = SDL_SCANCODE_8,
        NUM_9 = SDL_SCANCODE_9,

        SPACE = SDL_SCANCODE_SPACE,
        LSHIFT = SDL_SCANCODE_LSHIFT,
        RSHIFT = SDL_SCANCODE_RSHIFT,
        LCTRL  = SDL_SCANCODE_LCTRL,
        RCTRL  = SDL_SCANCODE_RCTRL,
        LALT   = SDL_SCANCODE_LALT,
        RALT   = SDL_SCANCODE_RALT,
        ESCAPE = SDL_SCANCODE_ESCAPE,
        ENTER  = SDL_SCANCODE_RETURN,
        TAB    = SDL_SCANCODE_TAB,
        BACKSPACE = SDL_SCANCODE_BACKSPACE,

        UP    = SDL_SCANCODE_UP,
        DOWN  = SDL_SCANCODE_DOWN,
        LEFT  = SDL_SCANCODE_LEFT,
        RIGHT = SDL_SCANCODE_RIGHT
    };
}
